services:
  todolist:
    build: .
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: todolist
      DB_USERNAME: postgres
      DB_PASSWORD: 1341
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1341
      PGDATA: /var/lib/postgresql/data/pgdata