services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1341
      PGDATA: /var/lib/postgresql/data/pgdata